name: fist-actions
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: test
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps: 
     - name: check out repo
       uses: actions/checkout@v4
     - name: setup python
       uses: action/setup-python@v4
       with:
         python-version: '3.12'
     - name: Install Dependencies
       run: |
         python -m pip install --upgrade pip
         pip install pyyaml
     - name: Run Feed Generator
       run: | 
         Echo "hello world" 
     - name: Push Repo
       uses: | 
         git config user.name github-actions 
         git config user.email github-actions@github.com
         git add . 
         git commit -m "primer commit"
         git push
       
